# this docker file creates the db-backup-job image

# start with the latest debian image
FROM debian:stable-slim

# get some credit
LABEL maintainer="Phil Owen (powen@renci.org)"

# update the image base
RUN apt-get update && apt-get -y upgrade

# install postgre
RUN apt -y install postgresql

# install an editor
RUN apt -y install nano