# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "irods-service.fullname" . }}
  labels:
    {{- include "irods-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "irods-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "irods-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainer }}
      initContainers:
        - name: load-test-env
          image: alpine/git
          command: ["/bin/sh", "-c"]
          args:
            - git clone --single-branch -- https://github.com/irods/irods_testing_environment.git {{ .Values.storage.testing.mountPath }}/tests;
              git clone --single-branch -- https://github.com/irods/irods.git {{ .Values.storage.testing.mountPath }}/runtime;
          volumeMounts:
          - name: {{ .Values.storage.testing.name }}
            mountPath: {{ .Values.storage.testing.mountPath }}
      {{- end }}
      containers:
        - name: {{ include "irods-service.fullname" . }}
          command: [ '/bin/bash' , '-c']
          {{- if .Values.serviceInit.isProvider }}
          args: [ '{{ .Values.serviceInit.initScriptMountPath }} && sleep infinity;' ]
          {{- else }}
          args: ['sleep infinity;']
          {{- end }}

          {{- if .Values.securityContext}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository}}{{ .Values.image.os }}-{{ .Values.image.os_version }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service }}
          ports:
            - name: primary-port
              containerPort: {{ .Values.service.primaryPort }}
              protocol: TCP
            - name: secondary-port
              containerPort: {{ .Values.service.secondaryPort }}
              protocol: TCP
            {{- range untilStep (int .Values.service.minPort) (int .Values.service.maxPort) 1 }}
            - name: svc-port-{{ . }}
              containerPort: {{ . }}
              protocol: TCP
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: init-irods-script
            mountPath: {{ .Values.serviceInit.initScriptMountPath }}
            subPath: {{ .Values.serviceInit.initScriptName | quote }}
          - name: init-service-script
            mountPath: {{ .Values.serviceInit.serviceInitMountPath }}
            subPath: {{ .Values.serviceInit.serviceInitName | quote }}
          - name: init-logging-script
            mountPath: /etc/rsyslog.d/00-irods.conf
            subPath: "00-irods.conf"
          - name: init-logcfg-script
            mountPath: /etc/logrotate.d/irods
            subPath: "irods"
          - name: dsd-script
            mountPath: /irods/dsd.py
            subPath: "dsd.py"
          - name: rsyslog
            mountPath: /etc/rsyslog.conf
            subPath: rsyslog.conf
          - name: 50-default
            mountPath: /etc/rsyslog.d/50-default.conf
            subPath: "50-default.conf"
          {{- if .Values.storage.var }}
          - name: {{ .Values.storage.var.name }}
            mountPath: {{ .Values.storage.var.mountPath }}
          {{- end }}
          {{- if .Values.storage.opt }}
          - name: {{ .Values.storage.opt.name }}
            mountPath: {{ .Values.storage.opt.mountPath }}
          {{- end }}
          {{- if .Values.storage.zone }}
          - name: {{ .Values.storage.zone.name }}
            mountPath: {{ .Values.storage.zone.mountPath }}
          {{- end }}
          {{- if .Values.storage.tmp }}
          - name: {{ .Values.storage.tmp.name }}
            mountPath: {{ .Values.storage.tmp.mountPath }}
          {{- end }}      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: init-irods-script
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 0777
        - name: init-service-script
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 0777
        - name: init-logging-script
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 0777
        - name: init-logcfg-script
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 0777
        - name: dsd-script
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 0777
        - name: 00-irods
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 511
        - name: 50-default
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 511
        - name: rsyslog
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 511
      {{- if .Values.storage.opt }}
        - name: {{ .Values.storage.opt.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-service.fullname" . }}-opt-pvc
      {{- end }}
      {{- if .Values.storage.var }}
        - name: {{ .Values.storage.var.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-service.fullname" . }}-var-pvc
      {{- end }}
      {{- if .Values.storage.zone }}
        - name: {{ .Values.storage.zone.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-service.fullname" . }}-zone-pvc
      {{- end }}
      {{- if .Values.storage.tmp }}
        - name: {{ .Values.storage.tmp.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-service.fullname" . }}-tmp-pvc
      {{- end }}