---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-pvc
spec:
  accessModes:
  - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
