# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

# Default values for irods-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: container-registry
  tag: latest
  pullPolicy: IfNotPresent
  os:
  os_version:

initContainer: false

serviceInit:
  isProvider: false
  isConsumer: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
podSecurityContext:
securityContext: {}
serviceAccount:
  create: false
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    ephemeral-storage: 512Mi
    cpu: 2000m
    memory: 16Gi
  requests:
    ephemeral-storage: 256Mi
    cpu: 250m
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


