# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

{{ if .Values.storage.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-db.fullname" . }}-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
    {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
    {{ end }}
{{ end }}
